name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          azcli-script: |
            az storage blob upload-batch \
              --account-name <your_storage_account_name> \
              --container-name '$web' \
              --source './' \
              --overwrite true

      # Alternative using 'azcopy'
      # - name: azcopy
      #   uses: azure/CLI@v1
      #   with:
      #     azcli-script: 